#!/usr/bin/env python3

"""
Read the csv files generated by wl_ugps_external_extension and create a bag with 2 transforms:
    map -> vessel, this depends on the GGA and HDT (soon: PASHR) messages
    vessel -> base_link, this depends on the g2_acoustic logs

The first GGA message defines the origin on the map frame. All other vessel poses are relative to this first message.

The bag is written to /tmp/bag1.

You can install python3-transforms3d from apt.
"""

import argparse
import csv
import math

import geometry_msgs.msg
import rclpy.serialization
import rclpy.time
import rosbag2_py
import tf2_msgs.msg
import transforms3d

import util


class State:
    def __init__(self, writer: rosbag2_py.SequentialWriter):
        self.writer = writer

        # The initial vessel GPS reading will define (0, 0) in the map frame
        self.gps0: tuple[float, float] | None = None

        # Outputs
        self.tf_map_vessel = geometry_msgs.msg.TransformStamped()
        self.tf_map_vessel.header.frame_id = 'map'
        self.tf_map_vessel.child_frame_id = 'vessel'

        self.tf_vessel_base = geometry_msgs.msg.TransformStamped()
        self.tf_vessel_base.header.frame_id = 'vessel'
        self.tf_vessel_base.child_frame_id = 'base_link'

        self.num_transforms = 0

    def write_transform_message(self, transform: geometry_msgs.msg.TransformStamped):
        tf_message = tf2_msgs.msg.TFMessage()
        tf_message.transforms.append(transform)
        self.writer.write('/tf',
                          rclpy.serialization.serialize_message(tf_message),
                          util.time_ros_to_ns(transform.header.stamp))
        self.num_transforms += 1

    def recv_gga(self, row):
        """
        Update the map -> vessel translation. Wait for the HDT message to write the transform to the bag.
        """
        gps = (float(row['latitude']), float(row['longitude']))

        if self.gps0 is None:
            # First GPS message defines the origin of the map frame
            self.gps0 = gps
        else:
            # Vessel position (x, y) in the map frame
            vessel_f_map = util.haversine(self.gps0, gps)

            # Convert NED -> ENU
            self.tf_map_vessel.transform.translation.x = vessel_f_map[1]
            self.tf_map_vessel.transform.translation.y = vessel_f_map[0]

    def recv_acoustic(self, row):
        """
        Update the vessel -> base transform, and write it to the bag.
        """
        util.time_s_to_ros(float(row['timestamp']), self.tf_vessel_base.header.stamp)

        # Convert NED->ENU
        self.tf_vessel_base.transform.translation.x = float(row['y'])
        self.tf_vessel_base.transform.translation.y = float(row['x'])
        self.tf_vessel_base.transform.translation.z = -float(row['z'])

        self.write_transform_message(self.tf_vessel_base)

    def recv_hdt(self, row):
        """
        Update the map -> vessel rotation, and write the transform to the bag.
        """
        util.time_s_to_ros(float(row['timestamp']), self.tf_map_vessel.header.stamp)

        # Rotate NED->ENU
        heading = util.norm_angle(math.radians(float(row['heading'])) + math.pi / 2.0)
        vessel_orientation = transforms3d.euler.euler2quat(0, 0, heading)

        # transforms3d quaternion is [w, x, y, z]
        self.tf_map_vessel.transform.rotation.w = vessel_orientation[0]
        self.tf_map_vessel.transform.rotation.x = vessel_orientation[1]
        self.tf_map_vessel.transform.rotation.y = vessel_orientation[2]
        self.tf_map_vessel.transform.rotation.z = vessel_orientation[3]

        self.write_transform_message(self.tf_map_vessel)


def wl_ugps_csv_to_bag(gga_path: str, hdt_path: str, acoustic_path: str, out_path: str):
    # Create a bag and open it for writing (append is not supported)
    writer = rosbag2_py.SequentialWriter()
    storage_options = rosbag2_py.StorageOptions(uri=out_path, storage_id='sqlite3')
    converter_options = rosbag2_py.ConverterOptions('', '')
    writer.open(storage_options, converter_options)

    # Create the /tf topic
    util.create_topic('/tf', writer, 'tf2_msgs/msg/TFMessage')

    # Create our state object
    state = State(writer)

    # Open the csv files we need
    gga_csv = open(gga_path, 'r', newline='')
    hdt_csv = open(hdt_path, 'r', newline='')
    acoustic_csv = open(acoustic_path, 'r', newline='')

    gga_reader = csv.DictReader(gga_csv, delimiter=',')
    hdt_reader = csv.DictReader(hdt_csv, delimiter=',')
    acoustic_reader = csv.DictReader(acoustic_csv, delimiter=',')

    # Get the first row from each csv file
    gga_row = next(gga_reader)
    hdt_row = next(hdt_reader)
    acoustic_row = next(acoustic_reader)

    # Merging the 3 csv files into a single bag. For each iteration find the earliest row, pop it and process it.
    try:
        while True:
            gga_s = float(gga_row['timestamp'])
            hdt_s = float(hdt_row['timestamp'])
            acoustic_s = float(acoustic_row['timestamp'])

            if gga_s < hdt_s and gga_s < acoustic_s:
                state.recv_gga(gga_row)
                gga_row = next(gga_reader)
            elif hdt_s < gga_s and hdt_s < acoustic_s:
                state.recv_hdt(hdt_row)
                hdt_row = next(hdt_reader)
            else:
                state.recv_acoustic(acoustic_row)
                acoustic_row = next(acoustic_reader)

    except StopIteration:
        print('Ran out of something, stopping')

    print(f'wrote {state.num_transforms} transforms')


def main():
    parser = argparse.ArgumentParser(formatter_class=argparse.RawDescriptionHelpFormatter, description=__doc__)
    # Hack for now...
    parser.add_argument('path')
    parser.add_argument('gga_filename')
    parser.add_argument('hdt_filename')
    parser.add_argument('acoustic_filename')
    args = parser.parse_args()
    gga_path = args.path + '/' + args.gga_filename
    hdt_path = args.path + '/' + args.hdt_filename
    acoustic_path = args.path + '/' + args.acoustic_filename
    wl_ugps_csv_to_bag(gga_path, hdt_path, acoustic_path, '/tmp/bag1')


if __name__ == '__main__':
    main()
